### ISSUE TITLE
Please publish a release (e.g.: v1.0)

### ISSUE THREAD

**Issue by ghost** [rfdeoliveira/procob-php#2]
Please create a tag and publish as a release (e.g: v1.0)

So we can monitor any new packages released and we don't get this message when installing with Composer:
> Could not find a matching version of package rfdeoliveira/procob-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by ronaldooliveiradevbr** [comment]
I just published a release tagged as v1.0.0. Could you please test if everything is ok, before I close this issue?

Thanks for reaching out =)

**Comment by ghost** [comment]
@rfdeoliveira mmm still not working

```bash
composer require rfdeoliveira/procob-php
```
```
In InitCommand.php line 727:                                                                               
  Could not find a matching version of package rfdeoliveira/procob-php. Check  
   the package spelling, your version constraint and that the package is avai  
  lable in a stability which matches your minimum-stability (stable).     
```

Have you published this project in packagist.org?

**Comment by ronaldooliveiradevbr** [comment]
Sorry, I haven't, because I thought you were trying to install it [this way](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository). I made it available on Packagist, it should be working now!
